function t(a,b){return Math.atan2(b.y-a.y,b.x-a.x)}function u(a){a%=360;return a<0?a+360:a}function v(a,b){if(typeof a==="undefined"||a===null)throw Error(b);return a}var w=0,x=class{constructor(a,b,d,f="linear"){this.M="linear";this.src=a;this.width=b;this.height=d;this.M=f;w++;this.id=w.toString()}dispose(){this.src.close?.()}};
function C(a,b){const {scale:d=1,M:f="linear"}=b??{};return new Promise(async g=>{try{const q=await fetch(a).then(m=>m.blob()),l=await createImageBitmap(q);if(d===1)g(l);else{var k=Math.round(l.width*d),n=Math.round(l.height*d),c=new OffscreenCanvas(k,n),e=c.getContext("2d");if(e){e.imageSmoothingEnabled=f==="linear";e.drawImage(l,0,0,k,n);var h=await createImageBitmap(c);l.close();g(h)}else g(l)}}catch(q){g(void 0)}})}var D=class{};
function E(a,b){if(a.g!==-1)throw Error("Ticker already running");const d=(f=performance.now())=>{let g;f>a.u?(g=f-a.u,a.X=g,g>a.l&&(g=a.l),a.v=g*.06*a.speed):a.v=0;a.u=f;a.h.v=a.v;a.h.X=a.X;a.h.u=a.u;b(a.h);a.g=globalThis.requestAnimationFrame(d)};a.g=globalThis.requestAnimationFrame(d)}
var H=class{constructor(){this.l=100;this.speed=1;this.u=-1;this.v=1;this.g=-1;this.h={v:0,u:0,X:0};this.X=1/.06}dispose(){this.g!==-1&&(globalThis.cancelAnimationFrame(this.g),this.g=-1);this.u=-1}},I=class{constructor(a){this.cache=new Map;this.h=new Map;this.da=a;this.buffer=new OffscreenCanvas(100,100);this.g=v(this.buffer.getContext("2d"),"OffscreenCanvas context cannot be undefined!")}ea(a,b,d){const f=`${a.id}-${b}-${d}`;var g=this.cache.get(f);if(g)return g;g=a.M;const k=a.src;this.buffer.width=
a.width;this.buffer.height=a.height;this.g.clearRect(0,0,this.buffer.width,this.buffer.height);this.g.globalCompositeOperation="source-over";this.g.fillStyle=b;this.g.globalAlpha=d;this.g.fillRect(0,0,this.buffer.width,this.buffer.height);this.g.globalCompositeOperation="destination-atop";this.g.globalAlpha=1;this.g.imageSmoothingEnabled=g==="linear";this.g.drawImage(k,0,0);a=this.buffer.transferToImageBitmap();a=new x(a,this.buffer.width,this.buffer.height);this.cache.set(f,a);return a}dispose(){for(const a of this.cache.values())a.dispose();
this.cache.clear();this.h.clear()}};async function J(a,b){var d=a.la?"nearest":"linear",f=await C(b,{M:d,...(void 0)});if(d=f?new x(f,f.width,f.height,d):void 0)b=b.substring(b.lastIndexOf("/")+1).split(/[?#]/)[0].replace(/\.[^/.]+$/,""),(f=a.g.get(b))&&f.dispose(),a.g.set(b,d);return d}
function K(a,b){const {ma:d,x:f=0,y:g=0,ja:k="#ff0000",Y:n=0,ka:c="#ffffff",C:e={x:0,y:0},scale:h=1,alpha:q=1}=b;a=a.L;var l=d*2;b=f-(e.x>=0&&e.x<=1?e.x*l:e.x)+d;l=g-(e.y>=0&&e.y<=1?e.y*l:e.y)+d;const m=typeof h==="number"?h:h.x,r=typeof h==="number"?h:h.y;m!==0&&r!==0&&q!==0&&(a.save(),a.globalAlpha=a.globalAlpha*q,m===1&&r===1||a.scale(m,r),a.beginPath(),a.arc(b,l,d,0,2*Math.PI),a.fillStyle=k,a.fill(),n>0&&(a.lineWidth=n,a.strokeStyle=c,a.stroke()),a.restore())}
function L(a,b){const {Z:d,x:f=0,y:g=0,rotate:k=0,width:n,height:c,C:e={x:0,y:0},scale:h=1,alpha:q=1,ua:l,ta:m=1,sa:r}=b,p=typeof d==="string"?v(a.g.get(d),`texture ${d} does not exist`):d;b=a.L;const y=n??p.width,z=c??p.height,F=e.x>=0&&e.x<=1?e.x*y:e.x,G=e.y>=0&&e.y<=1?e.y*z:e.y,A=typeof h==="number"?h:h.x,B=typeof h==="number"?h:h.y;A!==0&&B!==0&&q!==0&&(b.save(),b.globalAlpha=b.globalAlpha*q,b.translate(f,g),b.imageSmoothingEnabled=p.M==="linear",A===1&&B===1||b.scale(A,B),k>0&&b.rotate(k*Math.PI/
180),a=typeof l==="undefined"?p.src:a.h.ea(p,l,m).src,typeof a!=="undefined"&&(typeof r==="undefined"?b.drawImage(a,-F,-G,y,z):b.drawImage(a,r.x,r.y,r.width,r.height,-F,-G,y,z)),b.restore())}
var M=class{constructor(a){this.g=new Map;const {canvas:b,da:d,la:f=!1}=a;this.la=f;this.da=d;this.W={width:b.width,height:b.height};this.L=v(b.getContext("2d",{alpha:!1,willReadFrequently:!1}),"Unable to get 2D rendering context");this.h=new I(d)}ea(a,b,d){return this.h.ea(a,b,d)}dispose(){this.h.dispose();for(const a of this.g.values())a.dispose();this.g.clear();this.L=null}},O=class{constructor(a){this.g=a}async load(a){const b=a.N,d=a.width,f=a.height,g=a.Y;a=a.na;const k=d/2|0;try{const n=await J(this.g,
"./pucker.png"),c=await J(this.g,"./rsi_logo_center.png"),e=await J(this.g,"./star.png");return{ra:N(b,d,f,k,g,a),oa:n,pa:c,qa:e}}catch(n){}}};
function N(a,b,d,f,g,k){b+=g;d+=g;const n=new OffscreenCanvas(b,d),c=n.getContext("2d"),e=b/2,h=d/2,q=2*Math.PI/a.length;let l=0;c.save();a.forEach(m=>{const r=l+q;var p=c.createRadialGradient(e,h,0,e,h,f);p.addColorStop(0,m.i);p.addColorStop(1,m.j);c.beginPath();c.arc(e,h,f,l,r);c.lineTo(e,h);c.fillStyle=p;c.fill();c.closePath();c.save();c.fillStyle=m.i;c.font="bold 18px Arial";c.textAlign="right";c.textBaseline="middle";c.lineJoin="round";c.miterLimit=2;p=f-10;c.translate(e,h);c.rotate(l+q/2);c.strokeStyle=
"#fff";c.lineWidth=10;c.strokeText(m.label,p,2);c.strokeStyle="#122a53";c.lineWidth=6;c.strokeText(m.label,p,2);c.fillText(m.label,p,0);c.restore();l=r});l=0;c.lineWidth=g;c.strokeStyle=k;a.forEach(()=>{const m=l+q;c.beginPath();c.arc(e,h,f,l,m);c.lineTo(e,h);c.stroke();l=m});c.restore();c.save();c.beginPath();c.arc(e,h,37,0,2*Math.PI);c.fillStyle=k;c.fill();c.restore();a=n.transferToImageBitmap();return new x(a,b,d)}
var P=class{constructor(a,b){this.x=a;this.y=b;this.scale=2;this.speed=Math.floor(Math.random()*7)+6;this.angle=Math.floor(Math.random()*361)+0}update(a){this.angle+=.2*a;this.angle=u(this.angle);this.x+=Math.cos(this.angle*Math.PI/180)*this.speed*a;this.y+=Math.sin(this.angle*Math.PI/180)*this.speed*a;this.speed-=.001*a;this.scale>=.1&&(this.scale-=.08*a)}};function Q(a,b){const d=360/a.N.length;return 180/Math.PI*t(a.h,a.O)+(360-b*d-d/2)}
function R(a){for(let b=0;b<10;b++)a.l.push(new P(a.h.x,a.h.y))}function S(a,b){return new Promise(d=>{a.J=()=>{d()};a.D=b;a.ca=Q(a,a.D)})}
var T=class{constructor(a,b){this.F=!1;this.P=this.ga=this.fa=this.g=0;this.ca=-1;this.V=this.K=this.m=0;this.U=1;this.R=this.G=this.$=0;this.B=!1;this.H=this.o=this.I=this.ha=0;this.S=1;this.D=-1;this.l=[];this.ba=0;this.J=void 0;this.A=new M({canvas:a,da:new D});this.ia=new H;this.h={x:this.A.W.width/2,y:this.A.W.height/2};a=270*Math.PI/180;this.O={x:this.h.x+190*Math.cos(a),y:this.h.y+190*Math.sin(a)};this.ha=this.O.x;this.I=this.O.y;this.N=b;this.aa=this.A.L.createLinearGradient(0,0,340,340);
this.aa.addColorStop(0,"#546ff7");this.aa.addColorStop(1,"#2c2ee9")}async load(){this.T=await (new O(this.A)).load({N:this.N,width:340,height:340,Y:2,na:"#040f54"});E(this.ia,({v:a})=>{this.update(a);a=this.A;var b=a.L;b.save();b.fillStyle="#000";b.fillRect(0,0,a.W.width,a.W.height);b.restore();L(a,{Z:this.T.ra,x:this.h.x,y:this.h.y,C:{x:.5,y:.5},rotate:this.m});K(a,{x:this.h.x,y:this.h.y,ma:176,C:{x:.5,y:.5},ja:"rgba(0, 0, 0, 0)",Y:14,ka:"#040f54"});K(a,{x:this.h.x,y:this.h.y,ma:186,C:{x:.5,y:.5},
ja:"rgba(0, 0, 0, 0)",Y:10,ka:this.aa});L(a,{x:this.h.x,y:this.h.y,Z:this.T.pa,C:{x:.5,y:.5}});L(a,{x:this.ha,y:this.I,Z:this.T.oa,C:{x:.5,y:.4},rotate:this.o});for(b=0;b<this.l.length;b++){const d=this.l[b];L(a,{Z:this.T.qa,x:d.x,y:d.y,scale:d.scale,rotate:d.angle})}});this.m=Q(this,0)}dispose(){this.ia.dispose();this.A.dispose()}update(a){if(this.l.length>0){for(var b=this.l.length-1;b>=0;b--){const d=this.l[b];d.update(a);d.scale<=.1&&this.l.splice(b,1)}this.l.length===0&&(this.ba++,this.ba<2&&
R(this))}if(this.F){this.P+=a;this.m+=this.g*a;this.m=u(this.m);this.o-=(this.B?.1:.8)*a*this.S;this.o=u(this.o);this.H+=a;this.H>5&&(this.o=this.H=0,this.S*=-1);a:{b=this.D===-1?4:1.5;this.B||(this.g-=this.fa*a,this.g<=b&&(this.g=b));this.g<=-.3&&(this.g=-.3);if(!(this.P<this.ga||this.D===-1)){if(this.B)if(this.$<=3)this.G+=a,this.g+=this.R*a*this.K,this.g>=.3&&(this.g=.3),this.G>=60&&(this.$++,this.G=0,this.g/=2,this.R/=2,this.K*=-1);else{a=!0;break a}if(a=!this.B&&this.g<=b)a=Math.abs(u(this.m)-
u(this.ca)),a=Math.min(a,360-a)<=5;a&&(this.B=!0,this.K=this.D===Math.floor(u(180/Math.PI*t(this.h,this.O)-this.m)/(360/this.N.length))?-1:1)}a=!1}a&&(this.F=!1,this.g=0,this.J&&(this.J(),this.J=void 0))}else this.h.y+=.08*a*this.U,this.I+=.08*a*this.U,this.V+=a,this.V>=70&&(this.V=0,this.U*=-1)}};
async function U(){function a(){const e=d.getBoundingClientRect();k.style.left=`${e.left+(e.width-k.offsetWidth)/2}px`;k.style.top=`${e.bottom-80}px`;g.style.left=`${e.left+(e.width-340)/2}px`;g.style.top=`${e.top+20}px`}function b(){var e=window.innerWidth;const h=window.innerHeight;e<400||h<800?(e=Math.min(e/400,h/800),d.style.width=`${400*e|0}px`,d.style.height=`${800*e|0}px`):(d.style.width="400px",d.style.height="800px");a()}const d=document.createElement("canvas");d.width=400;d.height=800;Object.assign(d.style,
{display:"block",margin:"auto",position:"absolute",top:"0",bottom:"0",left:"0",right:"0",maxWidth:"100%",maxHeight:"100%"});Object.assign(document.body.style,{backgroundColor:"#1a1a1a",margin:"0",height:"100vh",overflow:"hidden"});document.body.appendChild(d);const f=document.createElement("div");Object.assign(f.style,{position:"absolute",top:"0",left:"0",width:"100%",height:"100%",pointerEvents:"none",zIndex:"10"});const g=document.createElement("img");g.src="./wheel_spin_logo.png";Object.assign(g.style,
{position:"absolute",transition:"all 0.1s ease"});document.body.appendChild(g);const k=document.createElement("button");k.textContent="Spin Now";Object.assign(k.style,{position:"absolute",padding:"15px 30px",fontSize:"18px",fontWeight:"bold",backgroundColor:"#139f35",color:"white",border:"none",borderRadius:"30px",cursor:"pointer",pointerEvents:"auto",transition:"all 0.1s ease"});f.appendChild(k);document.body.appendChild(f);window.addEventListener("resize",b);b();a();const n=[{label:"$100",i:"#ff8c69",
j:"#cc4f36"},{label:"Try Again",i:"#a26fdc",j:"#6e22b0"},{label:"$200",i:"#ffe45c",j:"#ccab00"},{label:"Free Spin",i:"#5cdbaa",j:"#308f5a"},{label:"$400",i:"#4fe0e3",j:"#00a3a6"},{label:"Lose a Turn",i:"#ff672c",j:"#cc3700"},{label:"$1000",i:"#ffbd9e",j:"#cc805f"},{label:"Spin Again",i:"#5baeff",j:"#1874cc"},{label:"$5000",i:"#f98cff",j:"#b300b3"},{label:"Bonus Game",i:"#9dff82",j:"#4caf50"},{label:"$50",i:"#ffa64d",j:"#cc5500"},{label:"Try Again",i:"#ffd966",j:"#e6b800"}],c=new T(d,n);await c.load();
k.addEventListener("click",async()=>{c.F||(k.style.display="none",c.F||(c.ga=4/16.66*1E3,c.P=0,c.g=6,c.fa=.01,c.$=0,c.G=0,c.R=.01,c.B=!1,c.K=1,c.D=-1,c.ca=-1,c.S=1,c.o=0,c.H=0,c.ba=0,c.I=c.O.y,c.J=void 0,c.F=!0,R(c)),await V(),await S(c,Math.floor(Math.random()*(n.length-1+1))+0),k.style.display="block")})}var V=()=>new Promise(a=>{setTimeout(()=>a(),2E3)});window.onload=()=>U();
